name: Deploy Storybook to Chromatic
on:
  push:
    branches:
      - dev
  pull_request:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Run Chromatic
        uses: chromaui/action@v11.3.0
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
          exitZeroOnChanges: true
