name: Run lighthouse CI When Push on PR to dev branch
on: 
  pull_request:
    branches:
      - dev
    types: [opened, edited, synchronize, reopened]

permissions:
    contents: read
    pull-requests: write 
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Use Node.js 20.10.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Install dependencies
        run: |
          yarn install --immutable --immutable-cache --check-cache

      - name: Add host "local.ludo.study"
        run: sudo echo "127.0.0.1 local.ludo.study" | sudo tee -a /etc/hosts
      
      - name: Install mkcert and set up certificates
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3-tools
          curl -JLO https://github.com/FiloSottile/mkcert/releases/download/v1.4.4/mkcert-v1.4.4-linux-amd64
          chmod +x mkcert-v1.4.4-linux-amd64
          sudo mv mkcert-v1.4.4-linux-amd64 /usr/local/bin/mkcert
          mkdir -p cert
          mkcert -install
          mkcert local.ludo.study
          mv local.ludo.study.pem ${{ github.workspace }}/cert/
          mv local.ludo.study-key.pem ${{ github.workspace }}/cert/
      
      - name: Check If CA and key exist
        run: |
          [ -f ${{ github.workspace }}/cert/local.ludo.study.pem ] && echo "local.ludo.study.pem exist." || echo "local.ludo.study.pem does not exist."
          [ -f ${{ github.workspace }}/cert/local.ludo.study-key.pem ] && echo "local.ludo.study-key.pem exist." || echo "local.ludo.study-key.pem does not exist."

      - name: Start server and wait
        run: |
          yarn start:mac & # Run server in background
          echo "Waiting for server to start..."
          sleep 30 # Adjust sleep duration as needed

      - name: Test server accessibility
        run: |
          curl -I https://local.ludo.study:3000/ || echo "Server is not accessible or SSL/TLS certificate might be invalid."
        
      - name: Build the project
        run: |
          yarn build

      - name: Run Lighthouse CI
        env:
          HOST: local.ludo.study
          HTTPS: true
          SSL_CRT_FILE: ${{ github.workspace }}/cert/local.ludo.study.pem
          SSL_KEY_FILE: ${{ github.workspace }}/cert/local.ludo.study-key.pem
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          yarn global add @lhci/cli
          lhci autorun || echo "Fail to Run Lighthouse CI!"
          
          
      - name: Collect and Display Server Logs
        run: |
            echo "Collecting server logs..."
            # Assuming the logs are available in a specific location or can be extracted
            # Adjust the log file location according to your setup
            cat /path/to/server/logs.log || echo "No server logs found."